name: Deploy static Nuxt site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: –¢–µ—Å—Ç
        run: |
          echo "$SSH_KEY" > key
          chmod 600 key
          echo "üîë –ü—É–±–ª–∏—á–Ω—ã–π –∫–ª—é—á –∏–∑ GitHub Secrets:"
          ssh-keygen -y -f key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "–£—Å–ø–µ—à–Ω–æ–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏–µ!"
            # cd /var/www/trip-checklist-frontend
            # git reset --hard
            # git pull origin main
            # npm install
            # npx nuxt generate
